### ISSUE TITLE
Watchers and Stars

### ISSUE THREAD

**Issue by JoeJohnRobert** [peter-murach/github#201]
Awesome gem. Having a great time using it. It seems, perhaps, that the `watchers_count` attribute actually corresponds to the `stargazers_count`. I've pasted the response I'm getting for `watchers_count` below. Currently, I have 4 watchers for this project and only 1 star. However, when I call on `watchers_count` it returns 1 to me.  Thanks

```ruby
2.1.2 :007 > Github.repos.list(user: "JoeJohnRobert")[1]['name']
 => "Closest"
2.1.2 :008 > Github.repos.list(user: "JoeJohnRobert")[1]['watchers_count']
 => 1
```

**Comment by peter-murach** [comment]
This doesn't seem like an issue with the library, the response body is generated by GitHub api. I have no influence over correctness of the response. Have you tried raising the issue with GitHub?
