### ISSUE TITLE
Pulling repository "Readme" files as html.

### ISSUE THREAD

**Issue by dzackgarza** [peter-murach/github#206]
Hello! This may be more of a question than an issue - with the usual HTTP API, it's possible to pull a repository's Readme.md as a formatted string of HTML. 

This can be done with curl using something like:

    curl https://api.github.com/#{github_username}/#{repository_name}/readme \ 
    -H "Accept: application/vnd.github.v3.html

Is there a straightforward way to accomplish something similar with this library?

**Comment by peter-murach** [comment]
How about:
```ruby
github = Github.new
github.repos.contents.readme 'username', 'reponame', accept: 'application/vnd.github.v3.html'
```
