### ISSUE TITLE
Cannot seem to upload asset, error message not helping

### ISSUE THREAD

**Issue by ianks** [peter-murach/github#208]
When trying to post an asset onto Github I am being met with this response
```
POST https://uploads.github.com/repos/ianks/octodown/releases/v1.0.4/assets?name=octodown-1.0.4-linux-x86.tar.gz: 404 Not Found (Github::Error::NotFound)
```

I can confirm that the release tag does indeed exists, and the files that I am giving it exist as well. 

Here is the code I am using to upload.

```ruby
github.repos.releases.assets.upload(
  'ianks',       # Owner
  'octodown',    # Repo
  "v#{version}", # ID
  file,          # Filepath (this is the full filepath from system root)
  name: Pathname.new(file).basename 
)
```

Any idea what is going sour here?

**Comment by craigjennings11** [comment]
Just a guess, but it looks like your `id` is wrong. The Github api expects a call to `POST https://<upload_url>/repos/:owner/:repo/releases/:id/assets?name=foo.zip` where `id` is the id of the release, not the tag name. Notice that when you get the details of the release back from github, you get data like this:

```
"upload_url": "https://uploads.github.com/repos/octocat/Hello-World/releases/1/assets{?name}",
"id": 1,
"tag_name": "v1.0.0",
```

and that the `id` in the given upload_url is the actual `id` of the release, not the `tag_name`.
