### ISSUE TITLE
get commit code based on Commit id

### ISSUE THREAD

**Issue by SaiVardhan** [peter-murach/github#210]
Hi,

I am new to Github api.  I need to get the committed tree code based on commit id.

I am using Github api gem, I am little bit confused on initiliazing the Github api. 
```
g = Github.new basic: 'login:password' returns an object and
g.repos also returns an object but cannot see the repo count or names in it.
``` 

Please help me in this case.

Thanks..

**Comment by peter-murach** [comment]
Hi @SaiVardhan, `repos` is just a scope and not a request. I have documented all the methods inside the api. Please read [documentation](http://www.rubydoc.info/github/peter-murach/github/master/Github/Client/Repos#list-instance_method)

**Comment by SaiVardhan** [comment]
Hi Peter,
Thanks for you reply. Had some idea on going through the documentation.
Is there any possibility to get the content based on commit id..
