### ISSUE TITLE
Merge Method returning '400 problems parsing JSON'?

### ISSUE THREAD

**Issue by davidji99** [peter-murach/github#222]
I believe I am passing the correct paramters below:
```
client.pull_requests.merge(user: "#{org_user}", repo: "#{repo}", number: "#{pull_request_number}")
```

However this always returns 400 problems parsing JSON'. Am I missing something here? Thanks!

**Comment by davidji99** [comment]
going to see if a gem update works.

**Comment by peter-murach** [comment]
Hi David, appologies but I'm super busy lately. Have you tried looking up docs for parameters to pass - [see](https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged) . Maybe it is worth to first detect if merge can be done [see source](https://github.com/peter-murach/github/blob/master/lib/github_api/client/pull_requests.rb#L177) or even run `curl` by itself to see if your params are correct. Also you can pass `DEBUG=true` flag to see more output, specifically what parameters are actually passed along with the query - [see implementation](https://github.com/peter-murach/github/blob/master/lib/github_api/client/pull_requests.rb#L197). There is many things that can go wrong including broken JSON parser that you are using. If you find the problem at library level please submit a pull request!

**Comment by davidji99** [comment]
@peter-murach thanks for the tips. i'll check them out.

**Comment by camkidman** [comment]
@davidji99 Did you ever end up finding the issue with this? I'm running into the same issues on a separate method

`github.oauth.create scopes: ['repo']`

Yields a 422, UnprocessableEntity error, but running it without `scopes: ['repo']` yields:

`Github::Error::BadRequest: POST https://api.github.com/authorizations: 400 Problems parsing JSON`

Wondering if you made any headway on this when you were working on it and maybe took notes :laughing:
