### ISSUE TITLE
Support /teams/:id/memberships/:username

### ISSUE THREAD

**Issue by tu-vieja** [peter-murach/github#225]
Previous Github version [was deprecated] (https://developer.github.com/v3/orgs/teams/#add-team-member) on October '14 and now only works for members who are already part of the organization. Otherwise, the api returns 422 error code.

API v3 now has a new endpoint to support [memberships] (https://developer.github.com/v3/orgs/teams/#add-team-membership).

**Comment by jbrodie** [comment]
Has this been updated yet?  I would love to have this working.

**Comment by peter-murach** [comment]
I'd love to have this updated too. Is anyone willing to put in a pull request to get this sorted?

**Comment by peter-murach** [comment]
@jbrodie It's in the master as `add_memberhsip`, `team_memberhsip`, `remove_membership` soon to be released.
