### ISSUE TITLE
(bug) identity clash

### ISSUE THREAD

**Issue by altsheets** [peter-murach/github#230]
I was a bit surprised to see a random stranger (lmangani) here:

https://github.com/altsheets/hz-blockexplorer/commit/6bc2cd66225a55e5da0fa7729599270bbf312db5 and here
https://github.com/altsheets/hz-blockexplorer/commit/d1865453ba3fbb358ebc211f90ed26a83b732eb8#diff-56a3cbb556f8ed21a7c35e5ba5d04ce9

because I am sure that it was me (https://github.com/altsheets/) who did this commit. Using my username and password!

Then I asked him, and he has answered: "This happens a lot - it seems Github IDs as not so unique.... [...] this is just a display bug you can raise with Github [...]"

So. 
There is a bug. 
Wrong assignment of user identities to commits.

Thanks for your time. And your GREAT website!

:-)

**Comment by peter-murach** [comment]
Sorry I do not control actual GitHub API endpoints and this seems to have nothing to do with this library. Please contact the GitHub itself to sort this out.

**Comment by altsheets** [comment]
Thx a lot. And sorry for the wrong place for this posting.

> contact the GitHub itself to sort this out
I have. And they reacted.
Not sure they really want to sort that out, though.

Good luck with whatever you are doing! :-)
