### ISSUE TITLE
List repositories being starred

### ISSUE THREAD

**Issue by davidesantangelo** [peter-murach/github#232]
I want to know all the starred repository for a user like this https://developer.github.com/v3/activity/starring/#list-repositories-being-starred

**Comment by peter-murach** [comment]
Every api call is documented in rdoc inside the lib/github/client and corresponds with the official specification. Therefore to find starring lookup activity/starring.rb file - [starred](https://github.com/peter-murach/github/blob/master/lib/github_api/client/activity/starring.rb#L50)
