### ISSUE TITLE
/repos/:owner/:repo/commits/:sha Endpoint Missing

### ISSUE THREAD

**Issue by pik** [peter-murach/github#233]
There are two types of commits queries in the [github api](https://developer.github.com/v3/repos/commits/), one which lists multiple commits and where `sha:` can either specify a branch or strangely enough an explicit reference and still return an unfiltered list in the following format (the sha specification does not work correctly here?): 
```
https://api.github.com/repos/:owner/:repo/commits?sha=:sha
```

And the correct form which gives the exact commit: 

```
https://api.github.com/repos/:owner/:repo/commits/:sha
```

I may have missed something - but I don't seem to be able to access the later form using this gem.

**Comment by anuja-joshi** [comment]
@pik This end point is implemented at `class Client::Repos::Commits < API`
You can use that as:
     
     github = Github.new
     github.repos.commits.get 'user-name', 'repo-name', 'sha'
