### ISSUE TITLE
Missing API for Add/Update Organization Membership

### ISSUE THREAD

**Issue by bdevore** [peter-murach/github#238]
Hey, we're trying to use your API to work with our Enterprise Github installation and noticed that the following GitHub API method isn't included yet: https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership. I'm fairly to Ruby, but took a whirl at adding the method call to your API. I can send in a PR with my change, it was fairly minor.

**Comment by peter-murach** [comment]
As it appears all the member memberships endpoints are not implemented. You should be able to reproduce the current logic to add this and other endpoints to the library. In order for me to merge the PR it would need to include tests. For inspiration, you should find plenty test examples already in features and specs directories. Looking forward to reviewing.

**Comment by peter-murach** [comment]
Part of `v0.13.0` release. Try using the following:
```ruby
github = Github.new oauth_token: 'abc....'
github.orgs.memberships.add 'org-name', 'member-name', role: 'role'
```
