### ISSUE TITLE
How to get all editable repos for a user?

### ISSUE THREAD

**Issue by dankohn** [peter-murach/github#245]
I'm trying to get the list of every public repo that the user has permission to edit, whether their own repo or someone else's. I can get that from the Github API with this, because the OAUTH-TOKEN is connected to the user:
```
curl -H "Authorization: token OAUTH-TOKEN" https://api.github.com/user/repos?type=public
```

What is the equivalent with this library?
```ruby
github = Github.new oauth_token: 'OAUTH-TOKEN'
github.repos.list(user: 'dankohn').map(&:url)
=> ["https://api.github.com/repos/dankohn/bash_profile", "https://api.github.com/repos/dankohn/rails", "https://api.github.com/repos/dankohn/vagrant-nodemon"]
```
`repos.list` only gives me the repos that I own, not ones I have access to. `users.list` gives me information on myself but not the repos I can edit.

Thanks. CC to @skhakimov and @david-a-wheeler.

**Comment by Shwetakale** [comment]
@dankohn The api you are using 

    github = Github.new oauth_token: 'OAUTH-TOKEN'
    github.repos.list(user: 'dankohn').map(&:url)

will give you the list of public repos of specified user but here you want list of all repos of authenticated user. Don't pass argument user.

    github = Github.new oauth_token: 'OAUTH-TOKEN'
    github.repos.list.map(&:url)

**Comment by dankohn** [comment]
Yes, that perfectly addresses my issue. Thanks!

**Comment by dankohn** [comment]
Just a note that the actual syntax for matching all public repos for which the authenticated user has read access is:
```ruby
github.repos.list(type: 'public').map(&:url)
```

**Comment by Shwetakale** [comment]
:+1:

**Comment by peter-murach** [comment]
@Shwetakale Thank you helping out with queries! :heart:
