### ISSUE TITLE
Missing API for Get the latest release of repository

### ISSUE THREAD

**Issue by Shwetakale** [peter-murach/github#246]
It seems like [Get the latest release or repository](https://developer.github.com/v3/repos/releases/#get-the-latest-release) API is missing.

**Comment by peter-murach** [comment]
Thank you letting me know and your help with issues. Regarding PR, I will review and merge in a week's time. I just hit a busy patch and i'm travelling tomorrow but once back I should have time to look through issues and release new version.

**Comment by peter-murach** [comment]
This has been included in `v0.13.0` release.
