### ISSUE TITLE
Authorizations API For an User

### ISSUE THREAD

**Issue by anuja-joshi** [peter-murach/github#248]
To create a new authorization token which is not specific to OAuth application (i.e. personal access tokens) `note` parameter is mandatory, but this is not handled. The code snippet below which is added to documentation, raises `Github::Error::UnprocessableEntity` 

```
github = Github.new basic_auth: 'login:password'
github.oauth.create scopes: ['repo']
```

**Comment by beraboris** [comment]
You can work around this with:

```ruby
github = Github.new basic_auth: 'login:password'
github.oauth.create note: 'something-unique', scopes: ['repo']
```

**Comment by anuja-joshi** [comment]
@beraboris Yes, but it should raise `Github::Error::RequiredParams` if we don't pass `note` parameter.
