### ISSUE TITLE
Search user based on location.

### ISSUE THREAD

**Issue by datomnurdin** [peter-murach/github#251]
I just wondering, is it possible to search user based on location using this query and applied using your library.

https://api.github.com/search/users?q=malaysia

Please advice. Thank you.

**Comment by Shwetakale** [comment]
@datomnurdin Yes this is possible using this library.

This can be done using following code snippet.

     github = Github::Client::Search.new
     github.users(q: 'pune')

For more information about this end point [check this out](https://github.com/peter-murach/github/blob/master/lib/github_api/client/search.rb#L77).

**Comment by datomnurdin** [comment]
why it still return only few results?

**Comment by Shwetakale** [comment]
@datomnurdin check [this](https://developer.github.com/guides/traversing-with-pagination/#basics-of-pagination) github gives 30 results in result (because of pagination).

By using above API pass per_page and page (current page number) options to get more results

    github.users(q: 'pune', per_page: 100, page: 10)

You can get total_count in response of first call.

    response = github.users(q: 'pune', per_page: 100, page: 10)

    response.body["total_count"]
    => 836

Now based on per_page and total_count you can loop over to get all search results.

**Comment by datomnurdin** [comment]
I got this result, #<Hashie::Mash incomplete_results=false items=[] total_count=34>.

**Comment by Shwetakale** [comment]
What is per_page number in your configuration? 

    Github.per_page
    => 30

I think this is 0 in your case.

**Comment by datomnurdin** [comment]
I got 30. then how?

**Comment by Shwetakale** [comment]
Which version of gem you are using? I am using ```0.12.4``` and I am getting results.

**Comment by datomnurdin** [comment]
I got 30. then how? Actually I want to find all Malaysia's developer. Using this search will be around 2,782 users. https://github.com/search?utf8=%E2%9C%93&q=location%3Amalaysia&type=Users&ref=searchresults

My code

```
github = Github::Client::Search.new
    @data = github.users(q: 'malaysia', per_page: 100, page: 1)
```

I'm using gem 2.4.8. Is it correct? Please advice.

**Comment by Shwetakale** [comment]
Latest release of gem is ```0.12.4``` and how come you are using ```2.4.8``` ?

Use following to get location wise filtering

    github.users(q: 'location:malaysia')

This gives me count 2782

   github.users(q: 'location:malaysia').body["total_count"]
   => 2782

And it gives result in ```body["items"]``` with pagination default 30.

**Comment by datomnurdin** [comment]
sorry my mistake. right now i'm using 0.12.3. BTW it works!! My silly mistake, I forgot to put location.

```
github.users(q: 'location:malaysia')
```

Thanks again!!
