### ISSUE TITLE
Throwing a 401, I don't understand why

### ISSUE THREAD

**Issue by quentindemetz** [peter-murach/github#254]
My server stderr is showing the following output:
```
GET https://api.github.com/repos/pricematch/admin/branches?access_token=censored: 401 Bad credentials
/home/ubuntu/dash/vendor/ruby/2.2.0/gems/github_api-0.11.3/lib/github_api/response/raise_error.rb:14:in `on_complete'
```
But running the same request with curl on the command-line works and returns the API's JSON without a problem. Any hints ?

Thanks!

**Comment by MrAlexLau** [comment]
I'm having the same issue! Started happening yesterday for me.

**Comment by peter-murach** [comment]
@quentindemetz Looking at the snippet I would suggest running the code with the latest version `v0.12.4`, see how that fares?

**Comment by mattheworiordan** [comment]
This issue is fixed with `v0.12.4`

**Comment by MrAlexLau** [comment]
This worked for me, thanks all!

**Comment by peter-murach** [comment]
@quentindemetz Please let me know if the problem persists for you.

**Comment by quentindemetz** [comment]
I was held up by some conflicting dependencies, but this now seems fixed! Thanks!
