### ISSUE TITLE
Is there a way to add read-only SSH Deploy keys to a GitHub repository?

### ISSUE THREAD

**Issue by viktorbenei** [peter-murach/github#255]
GitHub introduced `read-only` Deployment keys recently and the v3 API does support registering read-only keys (https://developer.github.com/v3/repos/keys/#create) but I can't figure out a way to do it through this GEM.

Tried as a string key:

```
# Deploy key
github.repos.keys.create(
  owner,
  repo_slug,
  :title => "#{slug}@...",
  :key  => public_key,
  'read_only' => true
  )
```

and as a symbol

```
# Deploy key
github.repos.keys.create(
  owner,
  repo_slug,
  :title => "#{slug}@...",
  :key  => public_key,
  :read_only => true
  )
```

Both registers read write deployment keys.

Is it possible to define this parameter somewhere, to create a read-only Deployment key?

**Comment by Shwetakale** [comment]
@viktorbenei The way you are calling method is correct. but in [this method](https://github.com/peter-murach/github/blob/master/lib/github_api/client/repos/keys.rb#L60) only valid key options are permitted to pass API as argument and in [VALID_KEY_OPTIONS](https://github.com/peter-murach/github/blob/master/lib/github_api/client/repos/keys.rb#L6) read_only is not included.

So in gem if you will add read_only in VALID_KEY_OPTIONS you will be able to use this.

**Comment by peter-murach** [comment]
@viktorbenei @Shwetakale As Shweta pointed out, probably the `read_only` key gets wiped out, I will need to remove the valid key options as this introduces too many breaking changes going forward. Viktor, can you wait till tomorrow for a fix?

**Comment by viktorbenei** [comment]
Thank you both for your quick reply! Sure, we can wait a couple of days for a fix :)

**Comment by peter-murach** [comment]
I have referenced feature tests that prove that the manipulation of deployment keys works. One thing that got me was the format of the `key` option, you need to ensure that you prepend your key with the right key type like `ssh-rsa AAAB3...`. All changes available in `v0.13.0`.

**Comment by viktorbenei** [comment]
Thank you for your work, we really appreciate it, and we'll test it on Monday ASAP :)

**Comment by viktorbenei** [comment]
Tested, works perfectly! Thank you for your effort! 😊
