### ISSUE TITLE
Upload endpoint hardcoded - doesn't work with Github Enterprise

### ISSUE THREAD

**Issue by shadabahmed** [peter-murach/github#259]
Facing an issue when trying to upload asset to enterprise Github of my company. Digging down it appears that the upload endpoint is hardcoded:

https://github.com/peter-murach/github/blob/master/lib/github_api/client/repos/releases/assets.rb#L73

Is it possible to move it out to the config ? Something like `c.upload_endpoint` ?

**Comment by peter-murach** [comment]
Sounds good to me. Fancy submitting PR?

**Comment by shadabahmed** [comment]
Sent :+1:  Please have a look and suggest changes if any
